# Generated by Django 4.2.3 on 2023-09-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_project_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="pattern.jpg", null=True, upload_to=""
            ),
        ),
    ]
