# Generated by Django 4.2.3 on 2023-10-01 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_message"),
        ("projects", "0008_alter_review_options_review_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("owner", "project")},
        ),
    ]
